server:
  port: 8085

spring:
  data:
    mongodb:
      uri: mongodb+srv://b9048635:p1pPLXpUFQGMSSId@cluster0.man4orn.mongodb.net/authdb?retryWrites=true&w=majority&appName=Cluster0
      database: authdb

jwt:
  secret: dev-smartbalaram-jwt-secret-key-2025!  # ✅ For local only, not for prod
  expiration: 86400000         # 1 day in ms
